# Generated by Django 3.2.6 on 2021-08-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('moilenumber', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('adharno', models.BigIntegerField()),
                ('trainingtype', models.CharField(max_length=100)),
            ],
        ),
    ]
