# Generated by Django 3.2.6 on 2021-08-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date',
            field=models.DateField(default=2),
            preserve_default=False,
        ),
    ]
