# Generated by Django 3.2.6 on 2021-08-23 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GymApp', '0002_customer_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='moilenumber',
            new_name='mobilenumber',
        ),
    ]
