# Generated by Django 3.2.6 on 2021-08-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='snum',
            field=models.BigIntegerField(),
        ),
    ]
