# Generated by Django 3.2.6 on 2021-08-19 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mname',
            new_name='manufracturename',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pdes',
            new_name='productdes',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pname',
            new_name='productname',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sname',
            new_name='sellername',
        ),
    ]
