# Generated by Django 3.2.6 on 2021-08-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('add', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('phn', models.BigIntegerField()),
                ('dic', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('ano', models.BigIntegerField()),
            ],
        ),
    ]
